[package]
name = "feos"
version = "0.0.1"
authors = ["danielle kefford"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bootloader = "0.9.3"
